services:

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    # depends_on:
    #   - backend
    networks:
      - fakturki-network

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - fakturki-network

  database:
    image: mongo:6-jammy
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=admin
      - MONGODB_ADMIN_PASS=admin123
      - MONGODB_APPLICATION_DATABASE=FakturkiDB
      - MONGODB_APPLICATION_USER=Fakturki
      - MONGODB_APPLICATION_PASS=fakturki1234
    ports:
      - 27017:27017
    # volumes:
    #   - ./database/db:/data/db
    networks:
      - fakturki-network

  # volumes:
  #   fakturki-project:
  #     name: "fakturkidb"

networks:
  fakturki-network:
    driver: bridge