version: '3'

services:
  # Serwis bazy danych MongoDB
  mongodb:
    image: mongo:latest
    container_name: my-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: your_mongodb_username
      MONGO_INITDB_ROOT_PASSWORD: your_mongodb_password

  # Serwis backendu
  backend:
    build:
      context: ./backend
    container_name: my-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://your_mongodb_username:your_mongodb_password@mongodb:27017/your_database_name
    networks:
      - my-network

  # Serwis frontendu
  frontend:
    build:
      context: ./frontend
    container_name: my-frontend
    ports:
      - "80:80"
    networks:
      - my-network

networks:
  my-network: